### ISSUE TITLE
[Feature Request] Provide odometry data required for map building

### ISSUE THREAD

**Issue by wuehr1999** [107-systems/l3xz_gait_ctrl#16]
### ⚡ Feature Request

<p align="center">
  <a href="https://github.com/107-systems/107-Arduino-Viper"><img src="https://github.com/107-systems/.github/raw/main/logo/viper.jpg" width="20%"></a>
</p>

**Please Describe The Problem To Be Solved**
It would be a good idea to have additional odometry from the kinematic calculations of the robot driver, to improve other odometry data and mapping algorithms on the robot. Could You please publish an odometry message: http://docs.ros.org/en/noetic/api/nav_msgs/html/msg/Odometry.html

**Comment by aentinger** [comment]
Hi @pavel-kirienko :coffee: :wave: 

I may ask you to finish the work started in #25 during ENRICH :wink: (no pressure :stuck_out_tongue_closed_eyes: ). This would entail estimate the current position/motion of the robot from the gait control algorithm.
